#%RAML 1.0 Library
types:
  transaction: !include ../data-types/data-type-transaction.raml
  place: !include ../data-types/data-type-place.raml
  title: !include ../data-types/data-type-title.raml
  places:
    description: List of places (only id)
    type: place[] 
  titles:
    description: List of titles found in the search
    type: title[]