#%RAML 1.0 DataType
description: "Merchant's photos information"
properties:
  place_id: 
    type: string
    description: Universal identifier of places
    example: a13e5134142e064ce0c6659f38a8e04cac0a5e72f75a6672875f266347938cc7